### ISSUE TITLE
A matcher that checks that two arrays contain the same elements

### ISSUE THREAD

**Issue by denizdogan** [jest-community/jest-extended#114]
**Feature Request**

Description: A matcher that checks that two arrays contain the same elements. Examples:

```js
expect([1, 2]).toMatchArray([2, 1]) // order doesn't matter!
expect([1, 2, 2]).toMatchArray([2, 1, 2]) // same number of 2s, all good
expect([1, 2]).not.toMatchArray([1, 2, 2]) // one extra 2, FAIL
expect([1, 2, 2]).not.toMatchArray([1, 2]) // one extra 2, FAIL
```

Possible solution: Given arrays A and B, check that they are equal in length. For each element in A, check that the element is equal to any element in B. If it is, remove the element from both arrays. Loop until both arrays are empty.

**Comment by mattphillips** [comment]
Hey @denizdogan 

I like the sounds of this matcher! I'm not too sure about the name though, as `toMatchArray` sounds like it would need to be identical in terms of order.

How about something like `.toIncludeValues([values])`?

`jest-extended` currently has similar APIs in [`.toIncludeAllMembers([members])`](https://github.com/jest-community/jest-extended/tree/master/src/matchers/toIncludeAllMembers) and [`.toIncludeAnyMembers([members])`](https://github.com/jest-community/jest-extended/tree/master/src/matchers/toIncludeAnyMembers) which can be used for reference in terms of structuring the matcher.

How would you feel about sending a PR for this?

**Comment by denizdogan** [comment]
@mattphillips Yeah, I'm not sure what to call it, `.toIncludeValues` isn't 100% accurate either, it sounds like that's the same as `.toIncludeAllMembers` to me! :)

Maybe `.toEqualMembers`? It's hard to describe the matcher concisely. Sure, I can make a PR for this!

**Comment by mattphillips** [comment]
@denizdogan sorry missed the notification on this! I say lets just start a PR and we can decide on a name after 😆

**Comment by denizdogan** [comment]
@mattphillips Yeah, I'll start working on the PR today or tomorrow, I just had a lot of things to take care of IRL 👍

**Comment by mattphillips** [comment]
merged in #122

**Comment by AyobamiH** [comment]
I just started learning jest and I have been bashing my head against the keyboard before finding this, I still suffer from not being able to

**Comment by le0-0** [comment]
toContainEqual only checks that the supplied value (ONE value) is in the received array. The value you are expecting [0, 1] is not in the received array, which only contains numbers, not other arrays. The only values that are in the received value are 0 and 1.

These succeed:
`expect([0, 1]).toContainEqual(0)`
`expect([0, 1]).toContainEqual(1)`

This fails:
`expect([0, 1]).toContainEqual([0, 1])`
