### ISSUE TITLE
Date API Proposal

### ISSUE THREAD

**Issue by thiagodp** [jest-community/jest-extended#117]
**Feature Request**

Description:
API for Date matchers. Some matchers are inspired by [Jasmine Matchers](https://github.com/JamieMason/Jasmine-Matchers).

Possible solution:

Jasmine-like matchers:
```javascript
expect(date).toBeDate(); // Matcher added
expect(date).toBeValidDate();  // Matcher added

expect(date).toBeAfter(otherDate); // Matcher added
expect(date).toBeBefore(otherDate); // Matcher added

expect(object).toHaveDate(memberName);
expect(object).toHaveDateAfter(memberName, date);
expect(object).toHaveDateBefore(memberName, date);
```
Additional matchers:
```javascript
expect(date).toBeAfterOrEqualTo(otherDate); // or toBeGreaterThanOrEqualTo
expect(date).toBeBeforeOrEqualTo(otherDate); // or toBeLessThanOrEqualTo
expect(date).toBeBetween(startDate, endDate);
expect(date).toDiffInDays(otherDate, days); // e.g., expect( '12/25/2018' ).toDiffInDays( '12/24/2018', 1 );

expect( date ).toHaveDay( day );
expect( date ).toHaveMonth( month );
expect( date ).toHaveYear( year );
```

**Comment by mattphillips** [comment]
Nice one @thiagodp I like these a lot! Fancy sending a PR for any of them? :smile:

**Comment by thiagodp** [comment]
Hello @mattphillips ,
added #118 with `toBeDate()`. It's a first step, but I'll try to add more soon.

**Comment by CoreyKovalik** [comment]
I believe the following shouldn't pass, since 0 value unix codes are common bugs

This currently passes, but I believe should fail:
```
expect(new Date(0)).toBeValidDate()
```

**Comment by thiagodp** [comment]
Hi @CoreyKovalik, I think I disagree with you about `0` to be an invalid value. The Date API defines that argument as "an integer value that is the number of milliseconds since 1 January 1970 UTC". So, there is nothing wrong with it.

Whether an application could not accept it in order to avoid some kind of problem, a programmer should document that with a test case. However, the (Jest-extended) library should allow it, since it is an acceptable value for a Date.

**Comment by CoreyKovalik** [comment]
@thiagodp Was thinking along the lines of the same thing.  Would be nice to have a similar set of matchers for Unix timestamps

**Comment by thiagodp** [comment]
@CoreyKovalik yes, it would be useful to have such matchers

**Comment by dandv** [comment]
I'd like to propose a match for a timestamp being "within the last X ms". This is useful, for example, when testing that files like "createdAt" or "updatedAt" were properly updated within about the timestamp of the text.

I'm currently using

```js
expect(Date.now() - object.updatedAt).toBeLessThan(10 * 1000);
```

Proposed matcher:

```js
expect(object).toMatchObject({
  // ...
  updatedAt: expect.withinLast('10s'),
});

**Comment by RobertFischer** [comment]
Anyone working on this? @thiagodp @mattphillips @CoreyKovalik ?  If not, my work (@K4connect) is giving me some time to get these in, since they'd be useful for us.

**Comment by hansal7014** [comment]
Hi All,
I am new to open source development and would like to work on the 'toBeBetween' matcher. I can start working on this feature unless somebody is already working on it. 
Thanks.

**Comment by CoreyKovalik** [comment]
I'm not working on any of these currently, but I can share what pattern I've been using as a solution in production tests.

```javascript
const now = Date.now()
const response = fooFunctionToTest()
const nowDelta = Date.now() - now

expect(response.timestamp).toBeGreaterThanOrEqual(now)
expect(response.timestamp).toBeLessThanOrEqual(now + nowDelta)
```

It's been working for me for testing side effects in integration tests for values such as `createdAt` and `updatedAt`

**Comment by thiagodp** [comment]
Hi { @RobertFischer , @hansal7014 , @CoreyKovalik }, I'm not working on any of these either.

*Suggetion:* `toBeBetween(startDate, endDate)` could be defined as `toBeAfterOrEqualTo(startDate)` and `toBeBeforeOrEqualTo(endDate)`.

**Comment by hansal7014** [comment]
Hi @thiagodp @CoreyKovalik,

I'll start working on these matchers. Thanks for the suggestions.

**Comment by JamieMason** [comment]
Hi @thiagodp,
A newer typescript version of [Jasmine Matchers](https://github.com/JamieMason/Jasmine-Matchers) is at [expect-more-jasmine](https://github.com/JamieMason/expect-more/tree/master/packages/expect-more-jasmine/) and there is also a version for Jest is at [expect-more-jest](https://github.com/JamieMason/expect-more/tree/master/packages/expect-more-jest/). Some of the date matchers discussed here are featured there, feel free to take them if there is anything useful there.
