### ISSUE TITLE
`toContainAllKeys` will pass when tested against an empty object

### ISSUE THREAD

**Issue by LucianBuzzo** [jest-community/jest-extended#119]
**Bug**

- `package` version: 0.6.0
- `node` version: 9.6.1
- `npm` version: 5.6.0

`toContainAllKeys` will always pass when testing an empty object.
Here's a simple example to reproduce the issue.

```javascript
test('toContainAllKeys should fail', () => {
  expect({}).toContainAllKeys(['foo'])
})
```

I'll open a PR to fix this shortly

**Comment by mattphillips** [comment]
👍
