### ISSUE TITLE
Add node 6 in travis

### ISSUE THREAD

**Issue by mattphillips** [jest-community/jest-extended#123]
Currently snapshots fail in travis when running in node 6. This is because the colours being used in pretty-format are striped away from the snapshot. There is a related issue in Jest (see https://github.com/facebook/jest/issues/5431), which once fixed should resolve this issue and revert 0d8ac8b.

**Comment by dhuang612** [comment]
I would like to work on this

**Comment by keeganwitt** [comment]
Node 6 is no longer a relevant target, so we can close this issue. We are also using GitHub Actions now instead of Travis.
