### ISSUE TITLE
Improve setup instructions

### ISSUE THREAD

**Issue by franciscolourenco** [jest-community/jest-extended#125]
**Feature Request**

Description:
There is no documentation on how to setup if a custom `setupTestFrameworkScriptFile` is already being used.

Possible solution:
Improve docs

**Comment by mattphillips** [comment]
Hey @franciscolourenco good shout! I’ll update the docs with an example to fix this problem 😀

**Comment by istro** [comment]
@franciscolourenco First of all, thanks for the great work. I'd like to +1 this request, as I couldn't figure out how to add it if the config in parallel with another script we have at all :(. What I ended up doing is moving the other script into `setupFiles` array and it worked fine. However, it would be nice to know how to invoke all `jest-extended` setup manually (so I could just add it as a line inside our existing setup script).

**Comment by mattphillips** [comment]
I've just updated the docs to show how to setup `jest-extended` with other test framework scripts.

See: https://github.com/jest-community/jest-extended#setup
