### ISSUE TITLE
new expect toBeApproximate?

### ISSUE THREAD

**Issue by hustcc** [jest-community/jest-extended#126]
Example:

```js
expect(0.1 + 0.2).toApproximatelyEqual(0.3); // true

expect(Math.PI).toApproximatelyEqual(3); // true
expect(Math.PI).toApproximatelyEqual(3.1); // true
expect(Math.PI).toApproximatelyEqual(3.14); // true
```

or named `toCloseTo`?

It can be satisfied by toBeWithin, but not perfect!

**Comment by hustcc** [comment]
Whether pr is needed？

**Comment by mattphillips** [comment]
Hey @hustcc I like this, would you be able to supply a sentence in english of when you should use the matcher?

My concern is with the definition of `approximately` it seems quite loose, how approximate is the matcher? `0.1` or `0.01`?

Perhaps the matcher may benefit from `rounding`, `floor`, `ceiling` etc 🤷‍♂️

**Comment by hustcc** [comment]
> expect(value).toApproximatelyEqual(number);

get the `round` of `value`, with decimal digits of `number`. 

[fixed-round](https://www.npmjs.com/package/fixed-round) can be used.

**Comment by mattphillips** [comment]
@hustcc sorry I missed your reply! Do you want to close this or open it up with `help wanted`? 

I've not got the time at the moment to build this myself

**Comment by hustcc** [comment]
@mattphillips I hope you can reply whether you would consider adding this api to the project?

If yes, I can help to send a pr!
if no, I can close it, and then do myself. [jest-expect](https://github.com/hustcc/jest-expect)

**Comment by hustcc** [comment]
`toBeApproximate` should be a nice assert for Number.
