### ISSUE TITLE
Chaining multiple assertions

### ISSUE THREAD

**Issue by DarkLite1** [jest-community/jest-extended#127]
**Feature Request**

*Description:
Would it be possible to chain multiple assertions, one after the other?

Consider the following code:

```javascript
it('passes when value is a number', () => {
    const res = 1
    expect(res).toBeNumber(1)
    expect(res).toBe(1).toBeNumber()
})
```

It would be great if the last way of doing things was possible too. I'm very new to JavaScript. but I found the following example in the course material where they use the old version of `expect` (before it was Jest) with `mocha`:

`expect(res).toBe(1).toBeA('number');`

This way (`expect(res).toBe(1).toBeNumber()`) does not seem to be possible or maybe I'm missing something.

This would be convenient for negating a test, like so:
```javascript
it('passes when value is not number 1', () => {
    const res = 2
    expect(res).not.toBeNumber(1)
})
```

Thank you for your help.

**Comment by mattphillips** [comment]
Hey @DarkLite1 Jest core currently does not support chaining matchers (See https://github.com/facebook/jest/issues/3998)

For `jest-extended` to support them we would need the core matchers to also be chainable too which isn't going to be possible right now

**Comment by DarkLite1** [comment]
Thank you @mattphillips  for the feedback. After reading the other post I see there's support to implement this feature in jest core, although more and more people want it. Someone even suggested to write the code for it. I hope they reconsider their point of view on the matter.

**Comment by DarkLite1** [comment]
That's really great! I'm definitely going to give this a try. Thank you for the fast response 😊
