### ISSUE TITLE
Matchers don't show up in IntelliSense and tests don't typecheck

### ISSUE THREAD

**Issue by f0rr0** [jest-community/jest-extended#128]
**Bug**

- `package` version: 0.7.1
- `node` version: 10.1.0
- `npm` (or `yarn`) version: 1.6.0

What you did: Using `jest-extended` with `ts-jest`.

What happened (please provide anything you think will help): The new matchers don't show up in code hints and the typechecker complains about them not existing.

Reproduction repository (if possible): https://github.com/f0rr0/biostrap/blob/1db4b40dc1b091541f7a2ae36c931dbf83ce1432/src/activities/__tests__/reducer.test.ts#L36

**Comment by mattphillips** [comment]
Hey @f0rr0 I don't use Typescript so I'm not sure of the usual process for setting this up.

There was a similar question to this and answer [here](https://github.com/jest-community/jest-extended/pull/116#issuecomment-386810430). Let me know if that helps if not I will spend some time on the weekend looking into integrating TS with `jest-extended`

**Comment by Gecko222** [comment]
I have same problem in PhpStorm, i need to `import 'jest-extended';` :(

**Comment by salchichongallo** [comment]
Hi, just require the package in your setup file:
```js
// setupTests.js
require('jest-extended');
// ...
```
Typechecking should work.
