### ISSUE TITLE
Bug: toBeNumber() behaviour for Infinity and NaN

### ISSUE THREAD

**Issue by karl-chan** [jest-community/jest-extended#129]
**Bug**

- `package` version: 0.7.1
- `node` version: 9.10.1
- `npm` (or `yarn`) version: 5.7.1

Relevant code or config

```javascript
    expect(NaN).toBeNumber();
    expect(Infinity).toBeNumber();
```

What you did: The README suggests that `expect(NaN).toBeNumber()`  and `expect(Infinity).toBeNumber()` should pass.

What happened (please provide anything you think will help):
Both calls failed, with message:
```
Expected value to be a number received:
  NaN
Expected value to be a number received:
  Infinity
```

**Comment by mattphillips** [comment]
Thanks @karl-chan for raising this! I've just published a fix in [v0.7.2](https://github.com/jest-community/jest-extended/releases/tag/v0.7.2) 😄
