### ISSUE TITLE
Make toHaveBeenCalledBefore work with synchronous functions + support Jest 23

### ISSUE THREAD

**Issue by blikblum** [jest-community/jest-extended#131]
**Feature Request**

Description:
Currently toHaveBeenCalledBefore does not work if two functions are called in the same JS task due to is reliance on timestamp

Possible solution:
Jest 23 replaced timestamps by invocationCallOrder (https://github.com/facebook/jest/pull/5867). This allow to properly implement toHaveBeenCalledBefore. 

This will be necessary also to Jest 23 support

**Comment by mattphillips** [comment]
Hey @uc2pac this fix has been released today in [v0.8.0](https://www.npmjs.com/package/jest-extended/v/0.8.0) sorry for the delay!
