### ISSUE TITLE
toBeDate matcher not exported

### ISSUE THREAD

**Issue by tejasbubane** [jest-community/jest-extended#134]
The `toBeDate` matcher was added in https://github.com/jest-community/jest-extended/pull/118 but is not exported in  https://github.com/jest-community/jest-extended/blob/master/src/matchers/index.js.

Can we add some tests to make sure all matchers in the `src/matchers` directory are exported?

**Comment by mattphillips** [comment]
@tejasbubane I agree it would be great to get some sort of integration test around this or to automate the process of exporting everything - any ideas?
