### ISSUE TITLE
Random test failure with `toHaveBeenCalledBefore`

### ISSUE THREAD

**Issue by tejasbubane** [jest-community/jest-extended#136]
**Bug**

#### What you did:

PR: https://github.com/jest-community/jest-extended/pull/135

#### What happened (please provide anything you think will help):

Encountered unrelated build failure: https://travis-ci.org/jest-community/jest-extended/builds/387173049
Also saw this a couple times while running jest on local system.

**Comment by mattphillips** [comment]
Hey @tejasbubane thanks for reporting this should be fixed by #132 :smile:
