### ISSUE TITLE
New matchers: toHaveBeenCalledOnce and toHaveBeenCalledOnceWith

### ISSUE THREAD

**Issue by amercier** [jest-community/jest-extended#138]
I think it would be nice to add the following matchers for `Mock`:

### toHaveBeenCalledOnce

```js
const mock = jest.fn();
// ...
expect(mock).toHaveBeenCalledOnce();
```

that would be equivalent to:

```js
const mock = jest.fn();
// ...
expect(mock).toHaveBeenCalledTimes(1);
```

### toHaveBeenCalledOnceWith

```js
const mock = jest.fn();
// ...
expect(mock).toHaveBeenCalledOnceWith('foo', 'bar');
```

that would be equivalent to:

```js
const mock = jest.fn();
// ...
expect(mock).toHaveBeenCalledTimes(1);
expect(mock).toHaveBeenLastCalledWith('foo', 'bar');
```

### Rationale

I find myself regularly writing tests with only one call per mock. Especially while writing unit tests, where I prefer writing many small, atomic tests, rather than one large test for all cases.

**Comment by benjaminkay93** [comment]
if nothing else im happy to raise a pr for this

**Comment by Julian-Jurai** [comment]
We have something similar but not as semantic : 

```javascript
const mock = jest.fn();
expect(mock).toHaveBeenNthCalledWith(1, 'foo', 'bar');
```javascript

**Comment by mattphillips** [comment]
Sounds great! Feel free to send a PR with this, just drop a note here if you are working on it :smile:

**Comment by benjaminkay93** [comment]
Ive got a branch locally with a toHaveBeenCalledOnce matcher, it was queit straightforward, however the toHaveBeenCalledOnceWith is causing my brain issues, should we use === equality on objects or == equality on them?

**Comment by mattphillips** [comment]
@benjaminkay93 I think we probably want to do deep equality on them you can use the [`equals`](https://github.com/jest-community/jest-extended/blob/master/src/utils/index.js#L11) util to compare two objects deeply or the [`contains`](https://github.com/jest-community/jest-extended/blob/master/src/utils/index.js#L3) util to deeply check if an array contains an object

**Comment by benjaminkay93** [comment]
Sweet thank you @mattphillips, big help

**Comment by theryansmee** [comment]
@SimenB - I'll take a look at `toHaveBeenCalledOnceWith` 😊
