### ISSUE TITLE
Remove chalk to support browsers

### ISSUE THREAD

**Issue by frederickfogerty** [jest-community/jest-extended#139]
**Feature Request**

Description:

As jest is being used more and more in the browser, it would be great if this module could run in the browser. Currently this repo is blocking me due to its dependency on chalk. It seems that it's only used in [one place](https://github.com/jest-community/jest-extended/blob/3fdb02487c5bb5e4fa012c65c9eb519d963dc34e/src/index.js#L1)

Possible solution:

Remove the dependency on `chalk`.

**Comment by mattphillips** [comment]
Closing as #140 is now merged :tada:
