### ISSUE TITLE
New matcher: toBeNear(value, range)

### ISSUE THREAD

**Issue by JShabtai** [jest-community/jest-extended#145]
**Feature Request**

Description:
It would be nice to have a way of checking that a value is "close enough" to the expected result (e.g. due to roundoff errors). Using toBeWithin() can accomplish this, but it's a fairly verbose way of doing it.
Possible solution:
Should be equivalent to .toBeWithin(value - range, value + range)

**Comment by benjaminkay93** [comment]
so something like this: 
```
describe('test examples', () => {
  it('toBeWithin simple', () => {
    const example = 1.25
    expect(Math.round(example)).toBeWithin(1, 2)
  })
  it('toBeWithin complex', () => {
    const example = 1.25
    const range = 1
    expect(Math.round(example)).toBeWithin(example - range, example + range)
  })

  it('toBeNear as toBeWithin', () => {
    const example = 1.25
    const range = 2
    expect(Math.round(example)).toBeWithin(example - range, example + range)
    // *** The toBeNear alternative ***
    // expect(Math.round(example)).toBeNear(example, range)
  })
})
```

**Comment by benjaminkay93** [comment]
so in short, these should all pass?
```
it('toBeNear', () => {
    expect(10.31415).toBeNear(10)
    expect(10.31415).toBeNear(10, 2)
    expect(10.31415).not.toBeNear(10, 0.3)
  })
```

**Comment by benjaminkay93** [comment]
fair, that that makes sense. I would like to see this myself, but i don't know what others would think

**Comment by mattphillips** [comment]
Hey @JShabtai @benjaminkay93 I like this matcher, nice work! I agree that the second range argument should be required. 

Do either of you fancy sending a PR for this?

**Comment by JShabtai** [comment]
I could give it a go, but I'm not sure when I'll have time. If nobody else wants to do it, I'll get around to it _eventuall,_ but that might be a while.

**Comment by JShabtai** [comment]
Looking at the `toBeCloseTo` matcher built into expect, I'm wondering if having two similar functions with similar names might cause too much confusion?

Frankly, I don't like that function, since it takes the number of decimal places to consider, rather than just a range (you may want to use this for large numbers with nothing after the decimal place, or ranges like 0.004 instead of 0.01 or 0.001), but having confusing names can potentially cause more problems than it solves. Thoughts?

**Comment by hustcc** [comment]
Same with: https://github.com/jest-community/jest-extended/issues/126

**Comment by mattphillips** [comment]
@natealcedo have you started on this yet? If not @marharyta your help will be greatly appreciated :)

**Comment by natealcedo** [comment]
hey @marharyta 	! Please go ahead. I was gonna do it over the weekend but I had other commitments. Just shoot if you need any help. :)

**Comment by mikecann** [comment]
Something like this does the trick I think?

```
export const expectApprox = (num: number, toEqual: number, degreeOfUncertaintly = 0.00001) => {
  const delta = Math.abs(num - toEqual);
  expect(delta).toBeLessThanOrEqual(degreeOfUncertaintly);
};
```

**Comment by phapp88** [comment]
I'd like to implement this. Should tests pass when the received value is equal to value plus or minus range?
```javascript
// should these tests pass or fail
test('toBeNear', () => {
  expect(1).toBeNear(2, 1);
  expect(3).toBeNear(2, 1);
});
```
Also, I think naming the second argument `epsilon` would make it slightly more clear. Any thoughts on that?

**Comment by JShabtai** [comment]
@phapp88 I don't think it should matter too much whether the bounds match, but I would lean towards saying the tests you posted should pass. This use case is already for fairly fuzzy tests, having one more passing value shouldn't be a problem.

I'm not sure if epsilon is a better name. I think that's really only going to be clear to people with a background in math/science. Maybe 'marginOfError', 'offset' or 'radius'?

**Comment by phapp88** [comment]
@JShabtai Yeah, you make a good point that epsilon might not be clear for some people. I think 'offset' works pretty well.

**Comment by dandv** [comment]
@brian-lives-outdoors has given a [solution on SO](https://stackoverflow.com/questions/53369407/include-tobecloseto-in-jest-tomatchobject), which I've been using successfully for the past several months.

**Comment by GerkinDev** [comment]
Is it still relevant ? Maybe this can be either closed for housekeeping purpose, or I could open a PR for this.

**Comment by JShabtai** [comment]
I think closing it makes the most sense. There are some reasonable alternatives in the comments above.

**Comment by dandv** [comment]
5 years later, I still need a matcher to test that A is within ±X of B.

I'm surprised this hasn't been implemented yet... apparently just because of potential confusion with `.toBeCloseTo`, which has a very different purpose, as its documentation shows?

Is this potential confusion a real problem? This would be a new matcher, with documentation explaining what it does. There are [far worse cases of real confusion](https://stackoverflow.com/questions/8685739/difference-between-dom-parentnode-and-parentelement#comment10800812_8685780) out there.
