### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by abenchi** [jest-community/jest-extended#154]
**Bug**

- `package` version: 0.8.1
- `node` version: 8.11.2
- `npm` (or `yarn`) version: 1.7.0

Relevant code or config

```javascript
      fetch.mockResponseOnce(JSON.stringify({ data: "data" }), {
        headers: {
          "access-token": "access-token",
          client: "client",
          uid: "uid"
        }
      });
      const wrapper = shallow(<AuthenticationProvider {...minProps} />);
      const setStateSpy = jest.spyOn(wrapper, "setState");

      await wrapper.instance().login();

      expect(localStorage.setItem).toHaveBeenCalledBefore(setStateSpy);
```

What you did: I want to verify that a function call to localStorage is performed before the setState.

What happened (please provide anything you think will help): This code works great with the version `0.7.2`. Once I upgrade to `0.8.0` or `0.8.1` this tests does not work any more. I have the error `TypeError: Cannot read property 'length' of undefined`

**Comment by benjaminkay93** [comment]
This was because of a breaking change in jest 23, removing the old method of how this function work, if you bump your jest version it should work fine :)

**Comment by abenchi** [comment]
Wow ok thanks @benjaminkay93 for your response. I will try it. Thanks again

**Comment by dep** [comment]
I am noticing the same problem on my test.  The `toHaveBeenCalledAfter` appears to be failing with the same error, `TypeError: Cannot read property 'length' of undefined`

Here's my spec:

```
it('should invoke functions with different keys serially', async () => {
  const add = createAdd();
  const delay = 10;

  const update1 = jest.fn(
    () => new Promise(resolve => setTimeout(resolve, delay))
  );
  const update2 = jest.fn(() => Promise.resolve());
  const update3 = jest.fn(
    () => new Promise(resolve => setTimeout(resolve, delay))
  );
  const complete = jest.fn(() => Promise.resolve());

  add('update', update1);
  add('update', update2);
  add('update', update3);
  add('complete', complete);

  await nextTick(delay);

  expect(update1).toBeCalled();
  expect(update2).not.toBeCalled();
  // expect(update3).toHaveBeenCalledAfter(update1);
  expect(complete).not.toBeCalled();

  await nextTick(delay);
  expect(update2).not.toBeCalled();
  // expect(complete).toHaveBeenCalledAfter(update3);
});
```

And here's my package.json

```
{
    ...
    "jest": "^23.6.0",
    "jest-canvas-mock": "^1.1.0",
    "jest-extended": "^0.11.0",
    "jest-junit": "^6.0.1",
    ...
}
```

**Comment by dep** [comment]
Downgrading to jest `23.5.0` seems to have fixed it for me.
