### ISSUE TITLE
toInclude fails in node v8.11.3

### ISSUE THREAD

**Issue by deser** [jest-community/jest-extended#156]
TypeError: string.includes is not a function

**Comment by mattphillips** [comment]
Hmmm strange! [`.includes`](https://node.green/#ES2015-built-in-extensions-String-prototype-methods-String-prototype-includes) should work fine in Node 8.

Would you mind sharing reproduction steps?

**Comment by deser** [comment]
Sorry guys, I passed object instead of string :)

**Comment by mattphillips** [comment]
:laughing: it’s all good. I’m planning on adding some type checking into jest-extended to catch this and give a better error message :)

**Comment by deser** [comment]
Yep, thanks 👍
