### ISSUE TITLE
Incorrect type definition for toSatisfy() and toSatisfyAll()

### ISSUE THREAD

**Issue by karl-chan** [jest-community/jest-extended#162]
**Bug**

- `package` version: 0.8.1
- `node` version: 8.11.3
- `npm` (or `yarn`) version: 6.1.0

##### Relevant code or config
The readme demonstrates that `toSatisfy()` and `toSatisfyAll()` should accept a predicate:
```javascript
test('passes when value passes given predicate', () => {
  const greaterThanOneButNotThree = n => n > 1 && n !== 3;
  expect(100).toSatisfy(greaterThanOneButNotThree);
  expect(0).not.toSatisfy(greaterThanOneButNotThree);
  expect(3).not.toSatisfy(greaterThanOneButNotThree);
});

```
but the TypeScript compiler complains (for this exact example):
`Argument of type '(n: any) => boolean' is not assignable to parameter of type '() => boolean'.`

##### What happened (please provide anything you think will help):
In `types/index.d.ts`, the definitions of `toSatisfy()` and `toSatisfyAll()` are incorrectly specified as:
```javascript
toSatisfy(predicate: () => boolean): R;
toSatisfyAll(predicate: () => boolean): R;
```
in which the predicate does not accept any argument.
##### Possible solution:
They should be 
```javascript
toSatisfy(predicate: (value: any) => boolean): R;
toSatisfyAll(predicate: (value: any) => boolean): R;
```

**Comment by benjaminkay93** [comment]
I believe this will be resolved in this pr https://github.com/jest-community/jest-extended/pull/163 as raised by @tony19

(This is just a note for whomever comes into this issue to look :) )

**Comment by mattphillips** [comment]
Closing as #163 is now merged, I’ll publish the fix in a couple of days as I’m AFK travelling atm
