### ISSUE TITLE
toBeHexadecimal is not a function

### ISSUE THREAD

**Issue by Jerome1337** [jest-community/jest-extended#166]
I'm using `toBeHexadecimal()`  but this produce this error

```
TypeError: expect(...).toBeHexadecimal is not a function
```
`toBeHexadecimal` function seem not inside the lastest release while the documentation is already updated.

Do you know when the next release will be done ?

**Comment by mattphillips** [comment]
Hey @Jerome1337 this matcher has just been released in [v0.9.0](https://www.npmjs.com/package/jest-extended/v/0.9.0) 🎉
