### ISSUE TITLE
Add instruction for TypeScript setup

### ISSUE THREAD

**Issue by victorsmirnov** [jest-community/jest-extended#172]
**Suggestion**

Update the documentation and add simple instruction how to use the `jest-extended` library with TypeScript maybe under the setup section.

- Types for the Typescript are included in the library, no need to install any additional type definition (like for example `@types/jest`).
- Import types with the command `import "jest-extended";` in test TypeScript files.

Let me know if I should do a pull request for the change in the read me file.
Or may be this is wrong or is not needed.

**Comment by mattphillips** [comment]
Hey @victorsmirnov feel free to send a PR adding this to the docs in the readme.

I assume this is the correct usage for Typescript (I don't use TS if you couldn't tell :wink:)

**Comment by pedro-mass** [comment]
@victorsmirnov Didn't work for me. I get this error when trying:
```
TypeError: jestExpect.extend is not a function
```

**Comment by yordis** [comment]
@mattphillips I see that you have the type definitations already.

Is this still an issue?

**Comment by mdazy** [comment]
@yordis , yes, the import is still necessary otherwise the extra matchers are not recognized.

**Comment by jdalrymple** [comment]
I also removed @types/jest and it errors out with:

```
    test/unit/infrastructure/RequestHelper.ts:67:1 - error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.
```

**Comment by juanmait** [comment]
I'm including it in `tsconfig.json` like this:
```json
{
  "compilerOptions": {
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/jest-extended"
    ]
  }
}
```

It's seems to work fine. No need to import it anywhere. Do you see any possible downside with this approach?

**Comment by lonix1** [comment]
@victorsmirnov Is there a way to import once globally for all tests, and avoid this: `import "jest-extended";`?

**Comment by mattphillips** [comment]
I've added the above guidance to the readme see: https://github.com/jest-community/jest-extended/blob/master/README.md#typescript

**Comment by pelx** [comment]
still does not work.

**Comment by anchnk** [comment]
@pelx What do you mean exactly by 

> still does not work 

Do you have a `tsconfig.json` file at the root of your project ? 
Do you have an error ? 
Is there any way to have a minimalistic repo in order to reproduce and troubleshoot the issue ?

**Comment by shaunluttin** [comment]
Instead of a `global.d.ts` file we can add this to our tsconfig.json file: 

```
{
  "compilerOptions": {
  "include": [
    "src/**/*.ts",
    "node_modules/jest-extended/types/**/*.d.ts"     // <------------------------
  ]
}

```

**Comment by gdanov** [comment]
> Instead of a `global.d.ts` file we can add this to our tsconfig.json file:
> 
> ```
> {
>   "compilerOptions": {
>   "include": [
>     "src/**/*.ts",
>     "node_modules/jest-extended/types/**/*.d.ts"     // <------------------------
>   ]
> }
> ```

solves the problem for me, just note the "include" must be at the root, not child of "compilerOptions" (see the reference https://code.visualstudio.com/docs/languages/jsconfig)

**Comment by jacekkk** [comment]
> Instead of a `global.d.ts` file we can add this to our tsconfig.json file:
> 
> ```
> {
>   "compilerOptions": {
>   "include": [
>     "src/**/*.ts",
>     "node_modules/jest-extended/types/**/*.d.ts"     // <------------------------
>   ]
> }
> ```

Only works if you don't have `node_modules` in `excluded` which you should have, so not really a solution.

**Comment by known-as-bmf** [comment]
My solution was:

`package.json`

```jsonc
{
  // ...
  "devDependencies": {
    // ...
    "@types/jest": "26.0.10",
    "jest-extended": "0.11.5",
    // ...
  },
  // ...
}
```

`tsconfig.json`

```jsonc
{
  // ...
  "compilerOptions": {
    // ...
    "types": ["jest", "jest-extended"]
    // ...
  }
  // ...
}

```

**Comment by johncrim** [comment]
I ran into the same issue - I'm pretty sure that both the current instructions are wrong, and a new bug is needed to fix typing imports so the matchers are recognized by editors eg VS Code.

To be clear, current the README instructions DO work for compiling and running tests, but I have not been successful after an hour+ of trial and error in getting VS Code to integrate the typings. I've tried everything listed above and a few other tweaks that have worked for typings in the past, and the only option that works is including `import "jest-extended";` at the top of every file that uses it (same as @andersr).

IMO this should be removed from the README:
```
###Typescript

If your editor does not recognise the custom jest-extended matchers, add a global.d.ts file to your project with:

import 'jest-extended';
```

b/c it doesn't work. 

It would be nice if the tsconfig.json `"types": ["jest", "jest-extended"]` approach worked, but it appears that the jest types are resolved from `node_modules/@types/jest`, and for `"jest-extended"` to work there would have to be a `node_modules/@types/jest-extended` directory containing the type definitions. So, we need an addition to definitelytyped, it seems.

**Comment by mikemaccana** [comment]
> the only option that works is including import "jest-extended"; at the top of every file that uses it (same as @andersr).

@johncrim @andersr what should the top of a TS file that uses matchers from jest-extended look like? I have tried

```
import 'jest-extended';

import * as matchers from 'jest-extended';
expect.extend(matchers);
```

But this still fails with 

```
File '/home/mike/Code/company/myapp/node_modules/jest-extended/types/index.d.ts' is not a module. ts(2306) 
```

**Comment by npwork** [comment]
In my case worked to add to jest.setup.ts

```typescript
import 'jest-extended'

import * as matchers from 'jest-extended/all'
expect.extend(matchers)

```

**Comment by roman-ianchenko** [comment]
In my case, ( typescript "compilerOptions" "target": "ES2020"), this helped:

in the tests file:
`import 'jest-extended';`

in the package.json:
```
{
...
  "devDependencies": {
    "@types/jest": "^29.2.2",
    "@types/node": "^18.7.6",
    "jest": "^29.2.2",
    "jest-extended": "^3.2.0",
    "ts-jest": "^29.0.3",
    "typescript": "^4.9.4"
  },
  "dependencies": {
    "ts-node": "^10.9.1"
  },
  "jest": {
    "setupFilesAfterEnv": [
        "jest-extended/all"
    ]
  }
}

```

**Comment by damiisdandy** [comment]
Create a file called `jest-extended.d.ts` or anything file name with the extension `.d.ts` and type in the following:

```javascript
/// <reference types="jest-extended" />
```
That solved it for me

**Comment by geiliev** [comment]
For me I just had to import the types in the `jest-setup.ts` file
```typescript
import 'jest-preset-angular/setup-jest';
import 'jest-extended/all';
import 'jest-extended/types';
```

**Comment by SunnyAureliusRichard** [comment]
I got it working for my project by adding this to `jest.config.js`: 
```
setupFilesAfterEnv: [ "<rootDir>/test/setupFilesAfterEnv.ts" ]
```

And then in the `setupFilesAfterEnv.ts` I have:
```
import 'jest-extended'
import 'jest-extended/all';
```
