### ISSUE TITLE
Update docs to remove usage of deprecated config key setupTestFrameworkScriptFile

### ISSUE THREAD

**Issue by abdelrahman-elkady** [jest-community/jest-extended#192]
**Feature Request**

Description: In the last release of Jest `24.0.0` the configuration for scripts to run before tests are changed, deprecating `setupTestFrameworkScriptFile: String` in favor of `setupFilesAfterEnv: []`

See: 
- [Jest docs](https://jestjs.io/docs/en/configuration.html#setupfilesafterenv-array)
- [The PR introducing the change](https://jestjs.io/docs/en/configuration.html#setupfilesafterenv-array)

Possible solution: Just the docs (README) should be updated to use the new API

**Comment by tpluscode** [comment]
What's the correct setup now?

**Comment by abdelrahman-elkady** [comment]
@tpluscode 

Use `setupFilesAfterEnv` to avoid deprecation, changes introduced in #193

**Comment by abdelrahman-elkady** [comment]
Resolved in #215
