### ISSUE TITLE
Generalized way to use any matched against keys from .toMatchObject

### ISSUE THREAD

**Issue by dandv** [jest-community/jest-extended#212]
**Feature Request**

From this [StackOverflow question](https://stackoverflow.com/questions/55556712/using-jest-matchers-in-tomatchobject):

How can I use any [Jest extend matcher](https://jestjs.io/docs/en/expect) within the [`.toMatchObject(object)`](https://jestjs.io/docs/en/expect#tomatchobjectobject) matcher?

For example, testing that an object has several fields, including a field `foo` > zero:

```js
expect({ a: 'b', c: 'd', foo: 3 }).toMatchObject({
  a: 'b',
  c: 'd',
  foo: expect.toBeGreaterThan(0),  // expect.toBeGreaterThan is not a function
});
```

I know I could write `expect(theObject.foo).toBeGreaterThan(0)`, but is there away to not break away the logic for testing `.foo` from the `.toMatchObject` call?

**Comment by mattphillips** [comment]
Hey @dandv I'm not sure this issues belongs in `jest-extended`, `toBeGreaterThan` is a core matcher built into Jest.

I've just checked and it doesn't seem to be available as an asymmetric matcher - perhaps you want to raise an issue/PR there to discuss making all core matchers available as asymmetric matchers?

I'm going to close this for now, but feel free to reopen if I have misunderstood anything :smile:
