### ISSUE TITLE
Setup for Create React App using setupTests file

### ISSUE THREAD

**Issue by ozimos** [jest-community/jest-extended#249]
**Feature Request**

Description:
Provide a way to setup jest-extended in a Create-React-App (CRA) project similar to [this method](https://github.com/testing-library/jest-dom#usage)  from React Testing Library. As of now, adding

`
import "jest-extended";
`
to the src/setupTests.js file does not work and CRA does not provide the option to manually configure the [setupFilesAfterEnv](https://jestjs.io/docs/en/configuration.html#setupfilesafterenv-array)

My current workaround is to modify the test script in package.json

`
    "test": "react-scripts test --setupFilesAfterEnv=jest-extended",
`

Possible solution:

**Comment by AlexeyKorkoza** [comment]
@ozimos your solution works. Thank you very much.

**Comment by jorahood** [comment]
It still should be documented in the installation section
