### ISSUE TITLE
promise test not showing the correct information

### ISSUE THREAD

**Issue by artoodeeto** [jest-community/jest-extended#256]
**Bug**

- `package` version:
```
"jest": "24.9.0",
"jest-extended": "0.11.2",
```
- `node` version:` v12.13.1`

- `npm` (or `yarn`) version: `npm 6.12.1`

Relevant code or config

hello hello. 😄 🐛 
```javascript
it('should throw an error if email is incorrect format', async () => {

    const user = User.create({
      username: 'bar',
      email: 'foo',
      password: 'password'
    });

    await expect(user.validateModel()).toReject();

  });
```

What you did:
im not sure if its my editor or `jest-extended` but I added a `await` before the expect it will show me
 this on my editor ![Screen Shot 2019-12-09 at 6 10 05 PM](https://user-images.githubusercontent.com/19770382/70489019-58d25600-1aaf-11ea-80a4-c5ccaa735d92.png)

but when I remove it and test it using `.toResolve` it will show an error or test didnt pass but it shows this.

![Screen Shot 2019-12-09 at 6 14 33 PM](https://user-images.githubusercontent.com/19770382/70489161-c2526480-1aaf-11ea-8de9-767acd890c81.png)

it should give me reds right? and instead of 5 it should show 4 pass and 1 fail in red???

--- 

so I test it again I added `await` with `toResolved` method shows this.

![Screen Shot 2019-12-09 at 6 16 55 PM](https://user-images.githubusercontent.com/19770382/70489261-16f5df80-1ab0-11ea-8e0d-8d4f7605a6c5.png)

this should be the correct information that im getting. this is weird. any ideas? but for sure that `validateModel()` is a promise call. what you think?

What happened (please provide anything you think will help):

Reproduction repository (if possible):

**Comment by overlookmotel** [comment]
`await expect(user.validateModel()).toReject();` is the correct thing to have in your test.

Then the test will pass if `user.validateModel()` promise rejects (which I think is what you want).

It's the "'await' has no effect" warning in your code editor which is incorrect.

I don't use Typescript, so I can't advise why that warning is appearing. But `jest-extended` is doing its job correctly.

**Comment by artoodeeto** [comment]
@overlookmotel thanks for this. My problem was is the jest vscode extension. giving me incorrect errors. thank you! will close this.

**Comment by artoodeeto** [comment]
@overlookmotel thanks for this. My problem was is the jest vscode extension. giving me incorrect errors. thank you! will close this.
