### ISSUE TITLE
Matchers error

### ISSUE THREAD

**Issue by kbradl16** [jest-community/jest-extended#264]
I get this error
`
node_modules/@types/jest/index.d.ts:730:15 - error TS2428: All declarations of 'Matchers' must have identical type parameters.

730     interface Matchers<R, T = {}> {
                  ~~~~~~~~

node_modules/jest-extended/types/index.d.ts:5:13 - error TS2428: All declarations of 'Matchers' must have identical type parameters.

5   interface Matchers<R, T = void> {
              ~~~~~~~~
`
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/index.d.ts#L730

@types/jest": "^24.9.1",
"jest-extended": "^0.11.4",

**Comment by kbradl16** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/39982#issuecomment-578285534

**Comment by mattphillips** [comment]
Fixed in: https://www.npmjs.com/package/jest-extended/v/0.11.5

I've remove `T` from our definition as it is not used and is defaulted in the global Jest types in DT

**Comment by tonyhallett** [comment]
@mattphillips 

Shouldn't you be using T for toContainEntry / toContainEntries / toContainAllEntries / toContainAnyEntries ?
