### ISSUE TITLE
Update typescript setup docs after breaking change in ts-jest 25.5.0

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [jest-community/jest-extended#282]
In ts-jest `25.5.0` there was a [breaking change](https://github.com/kulshekhar/ts-jest/blob/master/CHANGELOG.md#breaking-changes) that now requires to list any additional typings in the `files` property of the `tsconfig.json`. The docs should be updated accordingly.

**Comment by qqilihq** [comment]
Thanks for that, this solved my issue!

fyi: I’ve seen that the link in your description misses the URL: https://github.com/kulshekhar/ts-jest/blob/master/CHANGELOG.md#2550-2020-05-05
