### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by fiznool** [jest-community/jest-extended#314]
Just wondering on the status of the project?

There hasn't been a new release for over a year, yet there are over 330k downloads per week on npm.

**Comment by silverwind** [comment]
Seems there are no active maintainers, straightforward PRs like https://github.com/jest-community/jest-extended/pull/279 are not getting merged either. I guess some new maintainers should be appointed.

**Comment by danilofuchs** [comment]
Have anyone found an viable alternative or forked this one?

**Comment by keeganwitt** [comment]
Lemme see if I can get in contact with one of the current maintainers and see if we can figure something out. If I don't succeed, I guess I'll take a stab at a fork.

**Comment by danilofuchs** [comment]
It does look like https://github.com/JamieMason/expect-more/tree/master/packages/expect-more-jest/ is being actively maintained.

It was recommended by jest-community themselves though: https://github.com/jest-community/awesome-jest#matchers

**Comment by keeganwitt** [comment]
Interesting, I hadn't heard of that one. It has a lot fewer matchers though (48 vs jest-extended's 114).

**Comment by keeganwitt** [comment]
I've also started cloning things over to my fork, in case we're not able to get a response from anyone: https://github.com/keeganwitt/jest-extended.

**Comment by keeganwitt** [comment]
Related issue: #205.

**Comment by keeganwitt** [comment]
I think the project is in a better place now and we can close this issue.
