### ISSUE TITLE
Has .toStartWith() disappeared?

### ISSUE THREAD

**Issue by binarykitchen** [jest-community/jest-extended#373]
After bumping from v0.11.5 to v1.1.0 the `toStartWith` fn seem to have disappeared but this breaking change isn't mentioned in the changelogs huh?

**Comment by charliematters** [comment]
Seconded - it doesn't look like it's missing in the code, but jest is saying that it's not a function

**Comment by C0ZEN** [comment]
I have the same issue with `toBeFalse` and `toBeFunction`.

**Comment by dharkness** [comment]
These work for me with v1.1.0:

```
expect('foobar').toStartWith('foo')
expect(false).toBeFalse()
expect(() => 5).toBeFunction()
```

Here's my `yarn.lock` entry for it:

```
jest-extended@^1.1.0:
  version "1.1.0"
  resolved "https://registry.yarnpkg.com/jest-extended/-/jest-extended-1.1.0.tgz#85b6f33c3ca53c65087b34663d4118927e728db8"
  integrity sha512-rC1U9N4SYSFEiHJP3H0ZSbVAARwnjzBOFoluuFYePATsOJaX7PMMNiM9svS4WTgSNCIIVT3RWlWy+Y4W3zLsjg==
  dependencies:
    expect "^26.6.2"
    jest-diff "^27.2.5"
    jest-get-type "^27.0.6"
    jest-matcher-utils "^27.2.4"
```

**Comment by overlookmotel** [comment]
I had same problem. Seems API has changed in v1.x.

Previously: `setupFilesAfterEnv: [ 'jest-extended' ]`

Now: `setupFilesAfterEnv: [ 'jest-extended/all' ]`

This is noted [in README](https://github.com/jest-community/jest-extended#setup).

**Comment by SimenB** [comment]
Yeah, we don't extend just by importing anymore 🙂
