### ISSUE TITLE
Why toHaveBeenCalledAfter does not check that the mock has been called?

### ISSUE THREAD

**Issue by ziacik** [jest-community/jest-extended#379]
Hi. I would expect that a test like this exists for `toHaveBeenCalledAfter`:
Fail if the mock under test has not been called at all.

```typescript
  test('fails when given second mock that has not been called and a first mock that has been called', () => {
    const mock1 = jest.fn();
    const mock2 = jest.fn();
    mock1();
    expect(() => expect(mock2).toHaveBeenCalledAfter(mock1)).toThrowError();
  });
```

It is rather surprising for me that "toHaveBeenCalledAfter" does not imply "toHaveBeenCalled". 

With current behavior, I'm forced to write this:
```typescript
    expect(mock2).toHaveBeenCalled();
    expect(mock2).toHaveBeenCalledAfter(mock1);
```

**Comment by SimenB** [comment]
Seems like something we should do yeah. PR welcome! 😀

**Comment by theryansmee** [comment]
Hi @SimenB, please assign this to me 😊
