### ISSUE TITLE
New Matcher: .toIncludeRepeated(substring, times)

### ISSUE THREAD

**Issue by mattphillips** [jest-community/jest-extended#42]
**Feature Request**

### .toIncludeRepeated(substring, times)

Use `.toIncludeRepeated` when checking if a `String` includes the given `String` substring the correct number of times.

```js
test('passes when value includes substring n times', () => {
  expect('hello hello world').toIncludeRepeated('hello', 2);
  expect('hello hello world').not.toIncludeRepeated('hello', 1);
});
```

**Comment by hamiltondanielb** [comment]
I will take this one

**Comment by mattphillips** [comment]
Thanks @hamiltondanielb all yours! Don't forget to star ⭐️ and share :smile:

**Comment by mattphillips** [comment]
@hamiltondanielb last day to get a Hacktoberfest contribution for this 😛

**Comment by marcinlichwala** [comment]
@mattphillips @hamiltondanielb
I could gladly take this one if you have nothing against ;)

**Comment by mattphillips** [comment]
@marcinlichwala I'm happy for you to give it a go :smile:

**Comment by mattphillips** [comment]
I've added this matcher in f91bd4f708a73118599acbbb9628955aec49f924
