### ISSUE TITLE
Cannot get `pass` and `fail` to work as expected

### ISSUE THREAD

**Issue by metasean** [jest-community/jest-extended#428]
This is probably some silly typo on my part, but I've run out of debugging ideas, and I'm consistently getting the same errors, regardless of what I try.

# Bug

- `package` version: 2.0.0
- `node` version: 14.19.0 (and 14.18.1 on my local version)
- `npm` (or `yarn`) version: 7.17.0 (and 8.1.4 on my local version)

### Relevant code or config

[https://stackblitz.com/edit/node-gu67f1?file=test%2Fpass_fail.test.js](https://stackblitz.com/edit/node-gu67f1?file=test%2Fpass_fail.test.js) (must use a Chromium-based browser 😞, but it's the best online IDE for demonstrating the problem)

### What you did:

Set-up a pretty straight-forward test that passes without `pass` and a version with `pass`.

I tried configuring via a setup file importing all matchers, then a setup file importing just `pass` and `fail`, and finally I tried just importing them within the test file.  Each variation gives me the same error.

### What happened (please provide anything you think will help):

The version without `pass` works as expected, while the version with `pass` or `fail` fails due to: `Cannot read properties of undefined (reading 'pass')`, regardless of how I try to import and extend with jest-extended.

### Reproduction repository (if possible): 
[https://stackblitz.com/edit/node-gu67f1?file=test%2Fpass_fail.test.js](https://stackblitz.com/edit/node-gu67f1?file=test%2Fpass_fail.test.js) (must use a Chromium-based browser 😞, but it's the best online IDE for demonstrating the problem)

**Comment by keeganwitt** [comment]
For posterity, the example is
```javascript
describe("jest-extended's", () => {
  it('without pass, test actually works as expected', () => {
    expect(1).toBe(1);
  });

  it('with `pass`, a test that should pass is actually failing', () => {
    expect(1)
      .toBe(1)
      .pass('passes when it should')
      .fail("doesn't fail when it shouldn't");
  });

  it('without fail, test actually works as expected', () => {
    expect(1).toBe(2);
  });

  it('fail is also erroring out', () => {
    expect(1).toBe(2).fail('fails when it should');
  });
});
```
which has this result
```
 FAIL  test/pass_fail.test.js
  jest-extended's
    ✓ without pass, test actually works as expected (172 ms)
    ✕ with `pass`, a test that should pass is actually failing (173 ms)
    ✕ without fail, test actually works as expected (177 ms)
    ✕ fail is also erroring out (176 ms)
```

I don't understand the question. I would expect any test that had `fail()` in the assertions to fail.

**Comment by metasean** [comment]
@keeganwitt - Thank you!

I was completely misunderstanding the expectations for these!  
I was expecting them to output the `message` based on the test result, i.e. when the test passed, it would output the `pass` `message` and when it failed, it would output the `fail` `message`.
