### ISSUE TITLE
Small fix to index.d.ts: Fix type of array arguments to readonly

### ISSUE THREAD

**Issue by ilyub** [jest-community/jest-extended#462]
```
index.d.ts:
toBeOneOf<E = any>(members: E[]): R;
toIncludeAllMembers<E = any>(members: E[]): R;
...
```
Is it possible to fix types from "E[]" to "readonly E[]"?
This will allow to pass readonly array to matchers without getting typescript error.

"E[]" implies that toBeOneOf is going to modify array, but I am sure this is not so.
The same applies to other matchers.

**Comment by SimenB** [comment]
Sure! wanna send a PR?

**Comment by ilyub** [comment]
https://github.com/jest-community/jest-extended/pull/465
