### ISSUE TITLE
`toHaveBeenCalledOnceWith` naming is ambiguous

### ISSUE THREAD

**Issue by harry-gocity** [jest-community/jest-extended#529]
**Doc Update / Clarification and feature request for `toHaveBeenCalledNTimesWith`**

Just checked out the project as I was looking for a `toHaveBeenCalledNTimesWith` matcher, where `n` is most often 1. I think there's a bit of ambiguity around `toHaveBeenCalledOnceWith`.

- How it can be read: expect the mock function to have been called at most one time with specific arguments
- How it's [implemented](https://github.com/jest-community/jest-extended/blob/17bb7899857d047f78a528bbfd11ed7292f6c7a9/src/matchers/toHaveBeenCalledOnceWith.js#L40): expect the mock function to have been called only once, **and** when it was called, it should have been called with specific arguments.

In the former version - what I was after - the matcher doesn't care about how many times it was called in total, but it asserts that the mock should only have been called once with the arguments I provided.

It would be good to clarify this in the docks, and long-term a matcher like the former would be useful :)

**Comment by keeganwitt** [comment]
I think there is a matcher that does what you want that is built into Jest: https://jestjs.io/docs/expect#tohavebeencalledwitharg1-arg2-

I'm open to suggestions for a rename if there's something that would make this clearer.

**Comment by keeganwitt** [comment]
Maybe `toHaveBeenCalledExactlyOnceWith`?

**Comment by keeganwitt** [comment]
I'm starting to wonder if we shouldn't have added this matcher. What would you intuitively expect `not.toHaveBeenCalledOnceWith` to do? To fail if it was invoked more than once (regardless of value)? To fail fail if it was ever invoked with the value, even if it was invoked more times with other values?

**Comment by SimenB** [comment]
I agree `toHaveBeenCalledExactlyOnceWith` would have been a better name.

> What would you intuitively expect `not.toHaveBeenCalledOnceWith` to do?

`.not` inverses a matcher. So it should fail if "regular" passes and vice versa. So in this case if not called exactly once or if not called with the correct args.

**Comment by harry-gocity** [comment]
> I think there is a matcher that does what you want that is built into Jest: https://jestjs.io/docs/expect#tohavebeencalledwitharg1-arg2-

This is what I've been using before, but in this case was after something that checked the number of times it was called with those arguments too. I think `toHaveBeenCalledExactlyOnceWith` is a better name too for the current matcher, current `.not` behaviour is fine too. Just after a true `toHaveBeenCalledNTimesWith` matcher now!
