### ISSUE TITLE
Vitest TypeScript support for InverseAsymmetricMatchers

### ISSUE THREAD

**Issue by rluvaton** [jest-community/jest-extended#548]
- `package` version: 3.2.1
- `node` version: 18.12.1
- `npm` (or `yarn`) version: 8.19.2

What happened (please provide anything you think will help):

Typescript fail in this
```typescript
test('InverseAsymmetricMatchers', () => {
	expect({
		data: [1, 2]
	}).toEqual({

		// I get here:
		// Property 'toIncludeSameMembers' does not exist on type 'ExpectStatic'
		data: expect.toIncludeSameMembers([2, 1])
	})
});
```

the type failed:
```
Property 'toIncludeSameMembers' does not exist on type 'ExpectStatic'
```

Reproduction repository (if possible):
https://github.com/rluvaton/jest-extended-bug-548

just run:
```
npm install
npm start
```

**Comment by SimenB** [comment]
Happy to take a PR fixing this

**Comment by rluvaton** [comment]
I can try but one thing that can help me is how the regular marchers works with typescript, the types literally have jest in it:
```typescript
declare namespace jest {
```

I would expect something related to the [`expect`](https://www.npmjs.com/package/expect) package...

Great work BTW on all the jest stuff!

**Comment by SimenB** [comment]
Yeah, the types shipped with Jest itself uses `expect` (https://jestjs.io/docs/expect#expectextendmatchers), but _this_ package enhances types from `@types/jest`.

**Comment by rluvaton** [comment]
created a PR

**Comment by SimenB** [comment]
https://github.com/jest-community/jest-extended/releases/tag/v3.2.2

**Comment by rluvaton** [comment]
Happy to contribute to open source, hope to see you again
