### ISSUE TITLE
asymmetric matcher type definitions are not good (yet again)

### ISSUE THREAD

**Issue by hugebdu** [jest-community/jest-extended#550]
After the recent change, cannot be used as nested in `jest`.
See [this comment](https://github.com/jest-community/jest-extended/commit/4b3fa65011cd622bfc44b29d646cc8b34d4c4a93#r95426283).

**Comment by SimenB** [comment]
PR welcome to fix it 👍

**Comment by hugebdu** [comment]
@SimenB I'm not familiar with `vitest` and it's typings.
however this [PR](https://github.com/jest-community/jest-extended/pull/549) broke `jest` typings.

I could PR with a revert :)

**Comment by rluvaton** [comment]
Sorry 😬

Could you create a repro repo so I could take a look at it later today

**Comment by hugebdu** [comment]
> Could you create a repro repo so I could take a look at it later today and fix it

wil do
10x

**Comment by rluvaton** [comment]
@hugebdu could you please check if #551 working for you? it fixed it for me...

@SimenB Could you please review the PR 😄

**Comment by hugebdu** [comment]
@rluvaton negative. now I have
```
  ● Test suite failed to run

    test.spec.ts:17:7 - error TS2322: Type 'AsymmetricMatcher' is not assignable to type 'number'.

    17       baz: expect.toBeNumber()
             ~~~

      test.spec.ts:5:3
        5   baz?: number;
            ~~~
        The expected type comes from property 'baz' which is declared here on type 'Foo'

```

**Comment by hugebdu** [comment]
@rluvaton built-in asymmetric matchers (like `expect.stringContaining`) have `any` as return type

**Comment by rluvaton** [comment]
> @rluvaton built-in asymmetric matchers (like `expect.stringContaining`) have `any` as return type

Where do you see that?

https://github.com/facebook/jest/blob/9af2540f87e8e0d4f1e0528981529ad1bc30a28a/packages/expect/src/types.ts#L119

**Comment by rluvaton** [comment]
change to any, could you please retry?

**Comment by SimenB** [comment]
My guess is that they're `any` in `@types/jest`

**Comment by hugebdu** [comment]
@SimenB [indeed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/index.d.ts#L757)

**Comment by rluvaton** [comment]
thanks, so it's ready for review 😄

**Comment by SimenB** [comment]
https://github.com/jest-community/jest-extended/releases/tag/v3.2.3

**Comment by hugebdu** [comment]
@SimenB @rluvaton 
Thank you guys
