### ISSUE TITLE
`toHaveBeenCalledBefore` and `toHaveBeenCalledAfter` don't accept result of `jest.fn()`

### ISSUE THREAD

**Issue by Lukas-Kullmann** [jest-community/jest-extended#552]
# Bug

- `package` version: 3.2.3
- `node` version: 18.13.0
- `npm` (or `yarn`) version: 8.19.3

I want to use `toHaveBeenCalledBefore` (or `...After`) with the result of a `jest.fn()`. However, I get a typescript error.

```javascript
declare const myFn: (argument: string) => void;

expect(jest.fn()).toHaveBeenCalledAfter(jest.fn(myFn));
// ----- error is here -----------------^^^^^^^^^^^^^
```

This results in an error:

```
Argument of type 'Mock<void, [argument: string]>' is not assignable to parameter of type 'MockInstance<unknown, unknown[]>'.
  The types returned by 'getMockImplementation()' are incompatible between these types.
    Type '((argument: string) => void) | undefined' is not assignable to type '((...args: unknown[]) => unknown) | undefined'.
      Type '(argument: string) => void' is not assignable to type '(...args: unknown[]) => unknown'.
        Types of parameters 'argument' and 'args' are incompatible.
          Type 'unknown' is not assignable to type 'string'.(2345)
```

Here's a typescript playground link that basically reproduces the issue: [playground link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gWwJ4DEUAueAClgHMBXbEFDEzGASxQoEp4BeAPngDckzYAG4AUGJAAPAA7gMpAFYhMAOgBmKUu3aqMSABJR+IAEIg6AYSgQIIYAEF1GEDCUqMGrXkI7xE0EhYBGR0LGk5MAYySho6aKgUXE5eeABvMXh4fSMTcysbO0dnV1JsJDAAaxJlNQBZCsqASTDEsBAAHioUSpQkAHcUABp4bt6BlABtAF0eEfUoZggm9QA5JHxmGEwWwTAoDGZUAH4SACMkJDtE9hJBYXEAXwkxAHpX+EUqTHgoRCQZLh4Eh1NkABYIWpYDC4ORocEHeD9BAoCzAeAQuCqbFiQLQODwFBQWhoGRQdqfDzpTLwdTdKJHFC0lAdAAqIwAmvBpC4UMB4YlcDMeKRmNgZHZaPQDozTmRsapKGgSByUnxWbd4A0qmzOTx-FlWC4YAsKdrKmzuL8kpzuVJefzrULplbBXweXRHfh6YdUCNzS1MG1Ouz4By+BksllUf15dilSrNazxFG44qYBRlWGkyn4M8aUbXKaEOaAEoqKgQDDljBUGAs1kRmlZGFyEgAcjgtfr7dzWX4NioIBIyZp+cN9CL5JLjXLaErGBayHFdhc1NTreH8HbrGXEpALl7zYEg633VA6lY9lz4-ghZN061s4rVdZYJgA3XUc3HYw74GR6pgOEBDiQgo3hILawjOVRzgubJ8FwT6wS+1YHnWDZ8AAPshlRwa+-6xjhZaoUuSArgeIAGnek4PmajSWKgLj2rqYZ2g6ApJMKX5ZNAmDWLYKp9oghRZhyMzCawQYoO0WashJx6sHsMqoAJEAAPIwKAMAkCgNBnK4CmpnA85VlmDgwDAUC4B0JGmRgCH6mOkHZNB8DlsoUT2AAaqeCFWqy7GevCAAKH7YMwaAgAAMswlSdG68DHE68C6SAJgwLmm7uSoVwmMAvkgSGiHwIFHp8qF4WRTFcWdKw6iuPAACqfDJU18A4YFaUZdR97FrhgYYMGrFcuVjqCtxkZRhQB7mqsxIgNojAYCwbDCce5RVCQ5qMZOLGhuG1FZJtlSWNcbian+kVHTgz5RQol1gtdLnHXd+hwEtAhCKIL3wDNGABhRUpDb6WiaqQpAKgm2bcOqnA4eeICXqiP0bY0TRA-EKlaJocqQ-GGZiWqpWPc9aNVBj+7A9j6kyYtmgkPj6aZomsMkyQV1oOtqYnfNtCkEStDLatHAc09XO-SdNYYW+kWfZzN1S+h9aFUOpDAaB7PgmTPPPt2KCqyAtPtOrp4jqTEvk3huUQPlhum0VJBznlPl+Y2FuK3dLsFaexuLRrW7O7brtFQhHuS8+nkuD7RUO5rHnyCHQ5h2LOtRkrUdJ0bdNx4HICZzHyfu6nEtZM8jxAA)

I think the problem was introduced in #477 where the argument of `toHaveBeenCalledAfter` was changed from `jest.MockInstance<any, any[]>` to `jest.MockInstance<unknown, unknown[]>`.

If I change it back to the `any`s in my playground, I don't get the error.

# Workaround

I fixed it temporarily in our project by creating my own `.d.ts` file with the following content.
However, it would be great if the library could fix it.

```typescript
declare namespace jest {
  interface Matchers<R> {
    toHaveBeenCalledBefore(
      mock: jest.MockInstance<any, any[]>,
      failIfNoFirstInvocation?: boolean,
    ): R;
    toHaveBeenCalledAfter(
      mock: jest.MockInstance<any, any[]>,
      failIfNoFirstInvocation?: boolean,
    ): R;
  }
}
```

**Comment by keeganwitt** [comment]
Are you using ts-jest? Or Babel? I'm having trouble reproducing this problem.

**Comment by keeganwitt** [comment]
What's interesting is these work fine
```typescript
test('toHaveBeenCalledBefore', () => {
    const mock1 = jest.fn();
    const mock2 = jest.fn();
    mock1();
    mock2();
    expect(mock1).toHaveBeenCalledBefore(mock2);
});

test('toHaveBeenCalledAfter', () => {
    const mock1 = jest.fn();
    const mock2 = jest.fn();
    mock2();
    mock1();
    expect(mock1).toHaveBeenCalledAfter(mock2);
});
```
But this does not
```typescript
test('toHaveBeenCalledAfter and toHaveBeenCalledBefore with mockFunction', () => {
    const myFn = (arg: string) => void {};
    expect(jest.fn()).toHaveBeenCalledAfter(jest.fn(myFn));
    expect(jest.fn()).toHaveBeenCalledBefore(jest.fn(myFn));
});
```
