### ISSUE TITLE
Type of `fail` clashes with vitest

### ISSUE THREAD

**Issue by simon-abbott** [jest-community/jest-extended#554]
https://github.com/jest-community/jest-extended/pull/549 supposedly added support for vitest, but when I try to use the types it fails with the error `Named property 'fail' of types 'ExpectStatic' and 'AsymmetricMatchersContaining' are not identical.`

Since the `pass` and `fail` matchers are not implemented, could those definitions just be removed?

**Comment by SimenB** [comment]
Sure. Should clean up docs as well. Wanna send a PR?

**Comment by simon-abbott** [comment]
Hmm. Upon closer review it seems that it's more complicated that that... I'll open a PR, but it's going to take some refactoring.

**Comment by simon-abbott** [comment]
I updated to the latest version of vitest and it seems to work now. I guess vitest changed something. Either way this appears to no longer be an issue.
