### ISSUE TITLE
[Bug]: The second param of toHaveBeenCalledBefore/toHaveBeenCalledAfter has default value, but is not typed as optional

### ISSUE THREAD

**Issue by Yupeng-li** [jest-community/jest-extended#651]
**Bug**

- `package` version: 4.0.1
- `node` version: 18.17.0
- `npm` (or `yarn`) version: yarn 1.22.19

Relevant code or config

```javascript
expect(myFunction).toHaveBeenCalledAfter(anotherFunction)
```

**What you did:**
I used `toHaveBeenCalledAfter` and didn't provide `failIfNoSecondInvocation` as above.
**What happened** (please provide anything you think will help):

The doc says it's default to true, but I got typescript error complaining the missing param. The code here shows that the second param `failIfNoSecondInvocation` is required. https://github.com/jest-community/jest-extended/blob/main/types/index.d.ts#L149

**Comment by Blond11516** [comment]
I already have a PR open to fix this https://github.com/jest-community/jest-extended/pull/650
