### ISSUE TITLE
Declaration merging does not work without exporting the CustomMatchers interface.

### ISSUE THREAD

**Issue by cdierkens** [jest-community/jest-extended#652]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `jest-extended@4.0.1` for the project I'm working on.

In order for declaration merging to work, the `CustomMatchers` interface needs to be exported.

**Before**
<img width="489" alt="image" src="https://github.com/jest-community/jest-extended/assets/4812409/137eca62-23fd-41e2-ab59-e332c0be5894">

**After**
<img width="483" alt="image" src="https://github.com/jest-community/jest-extended/assets/4812409/2f8a012e-2423-40cd-9cad-c16754c8d888">

**Full .d.ts file**

```ts
import type { CustomMatchers } from "jest-extended";
import "vitest";

declare module "vitest" {
  interface Assertion<T = any> extends CustomMatchers<T> {}
  interface AsymmetricMatchersContaining<T = any> extends CustomMatchers<T> {}
}
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/jest-extended/types/index.d.ts b/node_modules/jest-extended/types/index.d.ts
index a0cef96..bc8722a 100644
--- a/node_modules/jest-extended/types/index.d.ts
+++ b/node_modules/jest-extended/types/index.d.ts
@@ -1,6 +1,6 @@
 /* eslint-disable @typescript-eslint/no-explicit-any */
 
-interface CustomMatchers<R> extends Record<string, any> {
+export interface CustomMatchers<R> extends Record<string, any> {
   /**
    * Note: Currently unimplemented
    * Passing assertion
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by cdierkens** [comment]
Closing this issue.

I was able to get declaration merging working with the following `jest-extended.d.ts` file.

```ts
import type CustomMatchers from "jest-extended";
import "vitest";

declare module "vitest" {
  interface Assertion<T = any> extends CustomMatchers<T> {}
  interface AsymmetricMatchersContaining<T = any> extends CustomMatchers<T> {}
  interface ExpectStatic extends CustomMatchers<T> {}
}
```

**Comment by charliematters** [comment]
Sorry to dig up a closed issue, but this looks like invalid TS to me?
``` typescript
 interface ExpectStatic extends CustomMatchers<T> {}
```
Typescript (5.1.6) has this error: `Cannot find name 'T'.ts(2304)`
