### ISSUE TITLE
Consider transferring to jest-community

### ISSUE THREAD

**Issue by thymikee** [jest-community/jest-extended#67]
**Feature Request**

Hey! This repo looks good, I like the idea of extended matchers.
We've recently created an organisation for community modules: [jest-community](https://github.com/jest-community).

How do you feel about transferring this repository there?

cc @orta @rogeliog @SimenB

**Comment by orta** [comment]
Oh yeah, what a great project - 👍

**Comment by mattphillips** [comment]
Hey @thymikee sorry about the delay in replying I wanted to get Hacktoberfest out the way!

I'd definitely be open to transferring jest-extended over to [jest-community](https://github.com/jest-community). I've never transferred a project before - how would it work with owning/maintaining the project and releases?

Ideally I would like to continue maintaining the project and making sure it is going in the direction I had hoped for, would I need to join the jest-community organisation to do that?

My only concern is that I would rather only certain people would be able to approve/merge pull requests and not everyone in the org, is that possible?

**Comment by SimenB** [comment]
Those of us who are collaborators on the jest project are admins, so we will have write access through that.

But I think I can speak for us when I say that we won't be merging PRs to this project (might review them, though 🙂) or requiring publish access.

It's more of a way of highlighting awesome projects (I'd love to have your `babel-jest-assertions` in there as well!), and maybe enabling them to become better by having them closer to core Jest, by it being more obvious to the collaborators what's difficult to solve in user-land

**Comment by orta** [comment]
> My only concern is that I would rather only certain people would be able to approve/merge pull requests and not everyone in the org, is that possible?

Yeah, that seems totally fine with me - it can't be done at GH level, but culturally that's totally acceptable. I'll add you as an org admin to jest-community. It would continue to be your repo, just consolidated with other big jest-y projects

**Comment by mattphillips** [comment]
@SimenB that all sounds fair - and I totally trust the Jest collaborators 😄

Thanks @orta I'll transfer the project over now 🎉

**Comment by rogeliog** [comment]
This is awesome!!! 🎉

**Comment by SimenB** [comment]
🎉
