### ISSUE TITLE
Use `test` instead of `it`

### ISSUE THREAD

**Issue by tejasbubane** [jest-community/jest-extended#90]
**Feature Request**

* Description:
Our README uses `test`, but our codebase has `it` at a few places.
The [Jest docs](https://facebook.github.io/jest/docs/en/getting-started.html) use `test` everywhere. Although `it` is just an alias of `test`, should we switch to using `test` everywhere in our codebase to make it consistent with our README (as well as the Jest docs)?

* Possible solution:
Use `test` instead of `it`

Let me know if you are ok with the change and I will send a PR.

**Comment by subinoy7** [comment]
i can do this...

**Comment by mattphillips** [comment]
@tejasbubane I'm pretty easy either way if you think it would help if we were consistent then for sure send a PR :smile:

**Comment by martiuslim** [comment]
@tejasbubane hope you don't mind I submitted a pr since it has been a month since you brought this up :smile:

**Comment by tejasbubane** [comment]
@martiuslim No worries 👍

**Comment by mattphillips** [comment]
Closing as merged :smile:
