### ISSUE TITLE
New matcher: .toHaveBeenCalledBefore(mock)

### ISSUE THREAD

**Issue by mattphillips** [jest-community/jest-extended#98]
**Feature Request**

### .toHaveBeenCalledBefore(mock)

Use `.toHaveBeenCalledBefore` when checking if a mock has been called before another mock. 

```js
it('calls mock1 before mock2', () => {
  const mock1 = jest.fn();
  const mock2 = jest.fn();

  mock1();
  mock2();
  mock1();

  expect(mock1).toHaveBeenCalledBefore(mock2);
});
```

**Comment by mattphillips** [comment]
taken from https://github.com/facebook/jest/issues/4402

**Comment by mattphillips** [comment]
Blocked pending internal timestamp support in Jest: https://github.com/facebook/jest/pull/4866

**Comment by tejasbubane** [comment]
I would like to work on this. Will keep an eye on the pending Jest issue.

**Comment by tejasbubane** [comment]
The PR is merged, should I wait for next release of jest?

**Comment by mattphillips** [comment]
@tejasbubane you could work on it now but we will have to sync merging/releasing this matcher with the next release of Jest. 

We should also probably add a note to the matcher docs that it will only be compatible with `>jest@22`

**Comment by ChrisCinelli** [comment]
I am getting:
```
    TypeError: expect(...).toHaveBeenCalledBefore is not a function
```

I ma using `jest@22.0.4` and `jest-extended@0.5.0`

**Comment by mattphillips** [comment]
Hey @ChrisCinelli this matcher hasn’t been implemented yet.

@tejasbubane jest@22 has landed now do you still want to work on this? If not I can look into getting it added tomorrow 😄

**Comment by ChrisCinelli** [comment]
Yes, I found out. 

But I have bad news:
```
        console.log(setup.mock.timestamps);
        console.log(middleware.mock.timestamps);
```

Yield to:

```
  console.log lib/middleware.spec.js:12
    [ 1515112206835 ]

  console.log lib/middleware.spec.js:13
    [ 1515112206835 ]
```

**Comment by ChrisCinelli** [comment]
If you want to be able to implement `. toHaveBeenCalledBefore`, you need that every call to an instance of `jest.fn()` to increment a global counter and saving itto `myFunc.mock.callOrder` (maybe ?)

**Comment by mattphillips** [comment]
@tejasbubane @ChrisCinelli I've added and published this matcher in v0.6.0 so I'm going to close this issue. 

@ChrisCinelli because of the calls to mocks happening in the same event loop the timestamps are identical - as you described. Because of this for this matcher to work it depends on the mock being asynchronous and ran in a different context. For example:

```js
const timeout = time => () => new Promise(res => setTimeout(() => res()), time);

it('calls mock1 before mock2', async () => {
  const mock1 = jest.fn(timeout(1));
  const mock2 = jest.fn(timeout(1));

  await mock1();
  await mock2();
  await mock1();

  expect(mock1).toHaveBeenCalledBefore(mock2);
});
```

**Comment by benjamin21st** [comment]
Wouldn't it be more scalable to implement an API for `.series` as opposed to limiting one is called before another? 

What if use cases come up for three calls? 1000?

**Comment by mattphillips** [comment]
Hey @benjamin21st feel free to open a new issue and propose the API that you think would be more scalable 😄
